#!/usr/bin/env bash

echo "*************************************************************************"
echo "Auditing npm packages..."

cd app || exit
echo "*************************************************************************"
echo "Running npm audit...."
npm audit

echo "Checking for loader-utils vulnerabilities..."
sleep 1
npm audit | grep "loader-utils" || echo "✅ No loader-utils vulnerabilities found!"
