#!/usr/bin/env bash

echo "*************************************************************************"
echo "Auditing npm packages..."

cd app || exit
echo "*************************************************************************"
echo "Running npm audit...."
npm audit

function audit_loader_utils() {
  npm audit | grep "loader-utils" || echo "✅ No loader-utils vulnerabilities found!"
}

echo "*************************************************************************"
echo "Checking for loader-utils vulnerabilities BEFORE running npm update..."
sleep 1
audit_loader_utils

echo "*************************************************************************"
echo "Running npm update..."
sleep 1
npm update
audit_loader_utils
