#!/usr/bin/env bash

echo "*************************************************************************"
echo "Cleaning workspace..."

cd get-hash || exit
rm -rf node_modules
rm -rf ./*.tgz
rm -rf package-lock.json
cp outdated-package-lock.json package-lock.json

cd ../app || exit
rm -rf node_modules
rm -rf package-lock.json
cp outdated-package-lock.json package-lock.json
cd ..
