#!/usr/bin/env bash

echo "*************************************************************************"
echo "Running exercise..."

./clean

cd get-hash || exit
npm ci
npm pack

cd ../app || exit
npm ci
npm start

cd ..
sleep 2

./audit-loader-utils

# Reset changes to package-lock caused by `npm update`
./clean