#!/usr/bin/env bash

echo "*************************************************************************"
echo "Running exercise..."

./clean

cd get-hash || exit
npm i
npm pack

cd ../app || exit
npm i
npm start

cd ..
sleep 2

./audit-loader-utils
